### ISSUE TITLE
TypeError when running model - Could not locate function 'mae'

### ISSUE THREAD

**Issue by Pmlu-CPH** [PolymatGIQ/ANN_reactivity_ratios#1]
Hi kiarashfa,

Super cool code. Tried out the webapp and work seamlessly, however when i tried to download it and run it on my own computer the following error is called.
Any idea why?

`TypeError: Could not locate function 'mae'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mae', 'registered_name': 'mae'}`

Best Philip

**Comment by kiarashfa** [comment]
Hi Philip,

Apologies for the late reply and thanks for your kind words about the code!
Regarding the error you're encountering when running it on your local machine, this error is likely due to a mismatch in TensorFlow/Keras versions. The 'mae' loss function may not be recognized properly in older versions.

Alternatively, you can replace the string 'mae' with the actual function in your code. Update this line:

`model.compile(loss='mae', optimizer='adam')`

to:

`from tensorflow.keras.losses import MeanAbsoluteError`
`model.compile(loss=MeanAbsoluteError(), optimizer='adam')`


Best regards,
Kiarash
